# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args:
        - --allow-multiple-documents
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-private-key

-   repo: local
    hooks:
    -   id: ruff_format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]

    -   id: ruff_check
        name: ruff check
        entry: ruff check --fix --preview
        language: system
        types: [python]

- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.22.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
