package cmd

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"syscall"
	"time"

	"github.com/scylladb/argus/cli/internal/logging"
	"github.com/scylladb/argus/cli/internal/services"
	"github.com/spf13/cobra"
)

const sshConnectProbeTimeout = 10 * time.Second

var (
	sshKeyPath    string
	sshTTLSeconds int
	sshTunnelID   string

	sshCmd = &cobra.Command{
		Use:   "ssh",
		Short: "SSH tunnel operations",
	}

	sshKeysCmd = &cobra.Command{
		Use:   "keys",
		Short: "Manage SSH keys used for Argus tunnel",
	}

	sshKeysListCmd = &cobra.Command{
		Use:   "list",
		Short: "Fetch authorized SSH keys",
		Annotations: map[string]string{
			SkipAuthRetryAnnotation: "true",
		},
		RunE: func(cmd *cobra.Command, _ []string) error {
			cmd.SilenceUsage = true
			ctx := cmd.Context()
			client := APIClientFrom(ctx)

			svc := services.NewSSHService(client)
			keys, err := svc.ListAuthorizedKeys(ctx, sshTunnelID)
			if err != nil {
				return err
			}

			_, _ = fmt.Fprint(cmd.OutOrStdout(), deduplicateKeys(keys))
			return nil
		},
	}

	sshKeysRegisterCmd = &cobra.Command{
		Use:   "register",
		Short: "Register local SSH public key",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cmd.SilenceUsage = true
			ctx := cmd.Context()
			client := APIClientFrom(ctx)
			out := OutputterFrom(ctx)

			svc := services.NewSSHService(client)
			state, _, err := svc.EnsureKey(ctx, sshKeyPath, sshTTLSeconds, false)
			if err != nil {
				return err
			}

			cfg, err := svc.RegisterTunnel(ctx, state.PublicKey, sshTTLSeconds, sshTunnelID)
			if err != nil {
				return err
			}

			return out.Write(cfg)
		},
	}

	sshConnectCmd = &cobra.Command{
		Use:   "connect",
		Short: "Start local SSH tunnel and print local port",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cmd.SilenceUsage = true
			ctx := cmd.Context()
			log := logging.For(LoggerFrom(ctx), "ssh-connect")
			client := APIClientFrom(ctx)

			svc := services.NewSSHService(client)
			state, _, err := svc.EnsureKey(ctx, sshKeyPath, sshTTLSeconds, false)
			if err != nil {
				return err
			}

			tunnelCfg, err := svc.RegisterTunnel(ctx, state.PublicKey, sshTTLSeconds, sshTunnelID)
			if err != nil {
				return err
			}

			localPort, err := services.FindFreeLocalPort()
			if err != nil {
				return err
			}

			knownHostsPath, err := svc.PrepareKnownHostsFile(ctx, tunnelCfg)
			if err != nil {
				return err
			}
			defer func() {
				_ = os.Remove(knownHostsPath)
			}()

			sshArgs := services.BuildSSHConnectArgs(tunnelCfg, state.PrivateKeyPath, localPort, knownHostsPath)
			fmt.Fprintln(cmd.ErrOrStderr(), "ssh "+strings.Join(sshArgs, " "))
			sshCmd := exec.CommandContext(ctx, "ssh", sshArgs...) //nolint:gosec // ssh args are generated by trusted CLI code
			sshCmd.Stdout = cmd.ErrOrStderr()
			sshCmd.Stderr = cmd.ErrOrStderr()
			// Run SSH in its own process group so Ctrl+C (SIGINT to the terminal
			// process group) does not race with our explicit Kill on context cancel.
			sshCmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}

			if err := sshCmd.Start(); err != nil {
				return err
			}
			// Kill the SSH process group when this function returns for any reason
			// (normal exit, error, Ctrl+C). Setpgid means the PGID == SSH's PID,
			// so -PID kills the whole group.
			defer func() {
				_ = syscall.Kill(-sshCmd.Process.Pid, syscall.SIGKILL)
			}()

			waitErrC := make(chan error, 1)
			go func() {
				waitErrC <- sshCmd.Wait()
			}()

			if err := waitForTunnelReadiness(ctx, localPort, waitErrC); err != nil {
				// Kill is a no-op if SSH already exited (e.g. Permission denied).
				// Do NOT drain waitErrC here: waitForTunnelReadiness may have
				// already consumed it, leaving the channel empty and causing a
				// deadlock. waitErrC is buffered(1) so the goroutine can always
				// write without blocking and will be GC'd with the channel.
				_ = sshCmd.Process.Kill()
				return err
			}

			_, _ = fmt.Fprintln(cmd.OutOrStdout(), localPort)
			log.Info().Int("local_port", localPort).Msg("ssh tunnel established")

			if err := <-waitErrC; err != nil {
				if ctx.Err() != nil {
					return ctx.Err()
				}
				if exitErr, ok := err.(*exec.ExitError); ok {
					if status, ok := exitErr.Sys().(syscall.WaitStatus); ok {
						return fmt.Errorf("ssh exited with status %d", status.ExitStatus())
					}
				}
				return err
			}

			return nil
		},
	}
)

func init() {
	defaultKeyPath, err := services.DefaultSSHPrivateKeyPath()
	if err != nil {
		defaultKeyPath = "~/.ssh/" + services.DefaultSSHPrivateKeyName
	}

	for _, c := range []*cobra.Command{sshKeysListCmd, sshKeysRegisterCmd, sshConnectCmd} {
		c.Flags().StringVar(&sshTunnelID, "tunnel-id", "", "Tunnel UUID override (optional)")
	}

	for _, c := range []*cobra.Command{sshKeysRegisterCmd, sshConnectCmd} {
		c.Flags().StringVar(&sshKeyPath, "key-path", defaultKeyPath, "Private key path")
		c.Flags().IntVar(&sshTTLSeconds, "ttl-seconds", services.DefaultSSHKeyTTLSeconds, "SSH key TTL in seconds")
	}

	sshKeysCmd.AddCommand(sshKeysListCmd, sshKeysRegisterCmd)
	sshCmd.AddCommand(sshKeysCmd, sshConnectCmd)
	rootCmd.AddCommand(sshCmd)
}

func deduplicateKeys(raw string) string {
	seen := make(map[string]struct{})
	var out []string
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if _, dup := seen[line]; !dup {
			seen[line] = struct{}{}
			out = append(out, line)
		}
	}
	if len(out) == 0 {
		return ""
	}
	return strings.Join(out, "\n") + "\n"
}

func waitForTunnelReadiness(ctx context.Context, port int, waitErrC <-chan error) error {
	readyCtx, cancel := context.WithTimeout(ctx, sshConnectProbeTimeout)
	defer cancel()

	readyErrC := make(chan error, 1)
	go func() {
		readyErrC <- services.WaitForLocalPort(readyCtx, port, sshConnectProbeTimeout)
	}()

	select {
	case err := <-waitErrC:
		if err == nil {
			return fmt.Errorf("ssh process exited before tunnel became ready")
		}
		return fmt.Errorf("ssh process exited before tunnel became ready: %w", err)
	case err := <-readyErrC:
		return err
	case <-ctx.Done():
		return ctx.Err()
	}
}
