[project]
name = "ArgusAI"
version = "0.1.0"
description = "Project incorporating varius AI capabilities into Argus to help with test runs investigation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=0.6.3",
    "scylla-driver>=3.28.0",
]
